language: dart
sudo: false
dart:
  - dev
addons:
  # otherwise a number of tests in test/security/html_sanitizer_test.dart fail
  firefox: "latest"
before_script: ./tool/travis_before_script.sh
dart_task:
  - test: -x codegen --platform vm
    xvfb: false
  # Disable parallelism on Firefox (-j 1)
  # Causes flakiness – need to investigate
  - test: -x codegen --platform firefox -j 1 -P safe_firefox
  - test: -x codegen --platform dartium
    install_dartium: true
  - dartfmt
  - dartanalyzer: --fatal-warnings lib
  - dartanalyzer:
  # TODO(kevmoo) Enable codegen tests when issue is fixed
  # https://github.com/dart-lang/angular2/issues/272
matrix:
  allow_failures:
    # Need to figure out how to exclude generated code in with known errors
    # in test directory
    - dart_task:
        dartanalyzer:
cache:
  directories:
    - $HOME/.pub-cache
