language: dart
sudo: false
dart:
  - stable
  - dev
  - 1.19.0
  - 1.18.1
  - 1.17.1
cache:
  directories:
    - $HOME/.pub-cache
with_content_shell: true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: ./tool/travis.sh
