language: dart
sudo: false
dart:
  - stable
  - dev
  - 1.19.0
env:
  - TEST_PLATFORM=vm
  - TEST_PLATFORM=content-shell
  - TEST_PLATFORM=firefox
cache:
  directories:
    - $HOME/.pub-cache
with_content_shell: true
addons:
  firefox: "latest"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 't=0; until (xdpyinfo -display :99 &> /dev/null || test $t -gt 10); do sleep 1; let t=$t+1; done'
script: ./tool/travis.sh
matrix:
  allow_failures:
  # Need compile timeout in pgk/test to be longer than 5 minutes
  - env: TEST_PLATFORM=firefox
  # content shell issues with latest dev - https://github.com/dart-lang/sdk/issues/27418
  - env: TEST_PLATFORM=content-shell
    dart: dev
